# Deploy the xampp container form eccod/xampp:latest

kind: PersistentVolume
apiVersion: v1
metadata:
    name: database
    labels:
        "qritserver/example": lamp
spec:
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: database
    labels:
        "qritserver/example": lamp
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi

---
# deploy the xampp server container
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: mysql
    labels:
        "qritserver/example": lamp
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - image: eccod/xampp:latest
                  imagePullPolicy: Always
                  name: mysql
                  resources:
                      requests:
                          cpu: 1
                          memory: 2Gi
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-credentials
                                key: rootpw
                      - name: MYSQL_USER
                        valueFrom:
                            secretKeyRef:
                                name: mysql-credentials
                                key: user
                      - name: MYSQL_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-credentials
                                key: password
                      - name: MYSQL_DATABASE
                        value: QRit
                  livenessProbe:
                      tcpSocket:
                          port: 3306
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - mountPath: /var/lib/mysql
                        subPath: data
                        name: database
            volumes:
                - name: database
                  persistentVolumeClaim:
                      claimName: database

---
apiVersion: v1
kind: Service
metadata:
    name: mysql
    labels:
        "qritserver/example": lamp
spec:
    type: ClusterIP
    ports:
        - port: 3306
          protocol: TCP
    selector:
        app: mysql