apiVersion: v1
kind: Service
metadata:
  name: {{ include "qrit-server.fullname" . }}
  labels:
{{ include "qrit-server.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "qrit-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
